future: true
permalink: /:title/
url: https://github.com/KAKE4420
name: Chenmy
author: Chenmy
qq: 442018735
email: chenmy5397@gmail.com

duoshuo: yourname
beian: 
cnzz: 
weibo: 
github: KAKE4420
about: "这里是 chenmy 的个人博客，创建于 2018 年。"

safe: true
paginate: 20
